### ISSUE TITLE
synergy surfboard <> Jina

### ISSUE THREAD

**Issue by hanxiao** [novoic/surfboard#12]
Hello there, first of all great work! 

I accidentally arrive here from one of the Python twitter accounts. I'm thinking about adding surfboard as one of audio feature extractors in Jina (https://github.com/jina-ai/jina). For some context, Jina is a universal neural search solution for *all kinds of data*, supporting audio2audio search is definitely in our scope. Perhaps we can co-work on some end-to-end demo as listed here (https://learn.jina.ai)?

Feel free to leave your comments and ideas in this thread.

**Comment by rlenain** [comment]
Hi there,
Thanks for being interested in Surfboard! 
Jina looks very interesting indeed. Do keep in mind that Surfboard is released under a slightly different license (GPL 3.0) to Jina!

Other than that, we'd be happy to answer any questions you might have regarding using Surfboard for your particular use case!
