### ISSUE TITLE
Extract_feature input args bug in notebook Tutorial1

### ISSUE THREAD

**Issue by sammaxwellxyz** [novoic/surfboard#14]
The extract_features function in the 6th code cell is called with a features_list argument, i believe it be should a components_list argument.

**Comment by rlenain** [comment]
Hi there,
Thanks very much for flagging that, I'll go ahead and fix it. 
In the future, feel free to raise a pull request :)

**Comment by rlenain** [comment]
Fixed. Thanks for your contribution to Surfboard!
