### ISSUE TITLE
Do not pin dependency versions

### ISSUE THREAD

**Issue by jonashaag** [novoic/surfboard#9]
Pinning dependencies of a library to an exact version (e.g., `pandas==1.0.1`) has many drawbacks, for example security issues. I see no reason why the dependencies have to be pinned for surfboard.

Maybe we can pin only the major versions, e.g. `pandas>=1,<2`.

**Comment by rlenain** [comment]
Thanks very much -- we'll consider this.

**Comment by rlenain** [comment]
Addressed in #13 . Thanks for the suggestion @jonashaag
